name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract package info
      run: |
        echo "PACKAGE_NAME=$(jq -r .name package.json)" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --target production --file Dockerfile --tag maseshi/${{ env.PACKAGE_NAME }}:${{ env.PACKAGE_VERSION }}
