name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: package-info
      uses: nyaa8/package-info@v1.0.0
      with:
        follow-symlinks: false

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --target production --file Dockerfile --tag maseshi/${{ env.PACKAGE_NAME }}:${{ env.PACKAGE_VERSION }}
