name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get package info
      id: package
      uses: codex-team/action-nodejs-package-info@v1.1

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --target production --file Dockerfile --tag maseshi/${{ steps.package.outputs.name }}:${{ steps.package.outputs.version }}
