name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build --file Dockerfile --target start --platform linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x --tag ${{ secrets.DOCKER_USERNAME@L }}/${{ github.event.repository.name@L }}:latest .
