# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: yumeko hosting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        API_KEY: ${{ secrets.API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        TOKEN: ${{ secrets.TOKEN }}
        YOUTUBE_API: ${{ secrets.YOUTUBE_API }}
      run: npm rm -f package-lock.json && npm install
      run: npm ci
      run: npm start
