name: "CITest"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .github/
      - package.json
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
    - run: npm ci
    - run: npm run build --if-present
    - name: Start testing the system
      run: npm test
      env:
        apiKey: ${{ secrets.APIKEY }}
        appId: ${{ secrets.APPID }}
        applicationId: ${{ secrets.APPLICATIONID }}
        authDomain: ${{ secrets.AUTHDOMAIN }}
        databaseURL: ${{ secrets.DATABASEURL }}
        measurementId: ${{ secrets.MEASUREMENTID }}
        messagingSenderId: ${{ secrets.MESSAGINGSENDERID }}
        password: ${{ secrets.PASSWORD }}
        projectId: ${{ secrets.PROJECTID }}
        publicKey: ${{ secrets.PUBLICKEY }}
        storageBucket: ${{ secrets.STORAGEBUCKET }}
        token: ${{ secrets.TOKEN }}
