name: Node.js CI

on:
  push:
    branches: [ stable ]
    paths-ignore:
      - README.md
      - .github/
      - package.json
  pull_request:
    branches: [ stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: "14.x"
    - run: npm ci
    - run: npm run build --if-present
    - name: Start testing the system
      run: npm test
      env:
        token: ${{ secrets.TOKEN }}
        apiKey: ${{ secrets.API_KEY }}
        databaseURL: ${{ secrets.DATABASE_URL }}
        projectId: ${{ secrets.PROJECT_ID }}
        password: ${{ secrets.PASSWORD }}
        youtubeApi: ${{ secrets.YOUTUBE_API }}
